# -*- coding: utf-8 -*-
"""Data Science BC HW 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Ddl4w1sUTQjOIVsa6pyE70CzbpZzLDA
"""

pip install jupyterlab

word=input("Enter the word:")
vowel=['a','e','i','o','u']
count=0
for i in word:
  if i in vowel:
    count+=1
print("The number of vowels in", word,"is", count)

animals=['tiger', 'elephant', 'monkey', 'zebra', 'panther']
a=""
for i in range(len(animals)):
  i=animals[i]
  a=i
  print(a.upper())

for i in range (1,21):
  if i%2!=0:
    print(i, "odd")
  elif i%2==0:
    print(i, "even")

word=input("Enter the word:")
if word[:] == word[::-1]:
  print("The word is a palindrome")
else:
  print("The word is not a palindrome")

a=int(input("Enter an integer:"))
b=int(input("Enter another integer:"))
def sum_of_integer(a,b):
  return a+b
print ("The sum of two integer is", sum_of_integer(a,b))